entryPoints:
  web:
    address: ':80'

serversTransport:
  insecureSkipVerify: true

log:
  filePath: "/logs/traefik.log"
  level: DEBUG

accessLog:
  filePath: "/logs/access.log"

providers:
  docker:
    watch: true
    exposedByDefault: false
    defaultRule: "Host(`{{ or (index .Labels \"host\") .Name }}.localtest.me`)"
  file:
    filename: "/data/api.yaml"

api:
  dashboard: true
